[project]
name = "pyopcua-server"
version = "0.1.0"
description = "Add your description here"
authors = [
  { name = "Chew Chee Wai", email = "chew.cheewai@ynytechnology.com.my" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncua==1.1.6",
    "psycopg2-binary==2.9.10",
    "pyyaml==6.0.2",
    "cffi==1.17.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/opcua_server"]

[tool.uv]
package = true

[project.scripts]
opcua_server = "opcua_server:main"
