[project]
name = "pyopcua-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncua>=1.1.5",
    "psycopg2-binary>=2.9.10",
    "pyyaml>=6.0.2",
]

[pyright.tool]
venvPath = [".venv"]
